# Generated by Django 2.1.2 on 2018-10-09 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('estado', models.CharField(max_length=75)),
                ('ciudad', models.CharField(max_length=75)),
                ('municipio', models.CharField(max_length=75)),
                ('cp', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=10)),
                ('cel', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('potencia', models.IntegerField()),
                ('precio', models.FloatField()),
                ('marca', models.CharField(max_length=50)),
                ('vmin', models.IntegerField()),
                ('vmax', models.IntegerField()),
                ('pmin', models.IntegerField()),
                ('pmax', models.IntegerField()),
                ('isc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=75)),
                ('estado', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=50)),
                ('potencia', models.IntegerField()),
                ('isc', models.FloatField()),
                ('voc', models.FloatField()),
                ('precio', models.FloatField()),
                ('vmp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.IntegerField()),
                ('potencia', models.IntegerField()),
                ('rpu', models.CharField(max_length=60)),
                ('consumos', models.CharField(max_length=25)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('potenciaABS', models.CharField(max_length=25)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.Cliente')),
                ('inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.Inversor')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.Panel')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('verano', models.IntegerField()),
                ('rango', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.Oficina')),
            ],
        ),
        migrations.AddField(
            model_name='propuesta',
            name='tarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.Tarifa'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.Vendedor'),
        ),
    ]
